### ISSUE TITLE
add CodeRED Facebook page and Twitter links

### ISSUE THREAD

**Issue by zmughal** [aaron7pm/CodeRED#15]
So that people can find the event and get updates.

**Comment by rodrigoargumedo** [comment]
Great point. @zmughal I would love to see that happen in action.

**Comment by zmughal** [comment]
Done! Closed by https://github.com/aaron7pm/CodeRED/commit/b70bd311bc5a9bd0952c621aa3bd6ec48f69c306. @aaron7pm++!
