### ISSUE TITLE
Mailchimp form has some tag misplacement

### ISSUE THREAD

**Issue by rodrigoargumedo** [aaron7pm/CodeRED#21]
In [index.html](https://github.com/aaron7pm/CodeRED/blob/gh-pages/index.html#L84-L101), Some tags are not aligned with each other. It's kinda hard to read on this situation. Not sure if this was written in a short time.

**Comment by aarondancer** [comment]
It's supposed to work. Some stray css breaks it. Doesn't really matter as of now, new website is coming for Fall 2015

**Comment by rodrigoargumedo** [comment]
Ah, ok gotcha. Also, make use of some LESS or SASS preprocessors in the next one. :heart:

**Comment by aarondancer** [comment]
:+1:

**Comment by aarondancer** [comment]
btw @rodrigoargumedo : https://github.com/aaron7pm/CodeRED-Fall-2015
http://aaron7pm.github.io/CodeRED-Fall-2015/

**Comment by rodrigoargumedo** [comment]
Should CodeRED turn into a organization repo? That's my only question.. for now. @aaron7pm

**Comment by zmughal** [comment]
I've been thinking of having it be in @HoustonHackers... ;-)

(there's another reason re: the CodeRED name... @aaron7pm knows...)
